name: Check Matrix

on:
  pull_request: {}

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019]
        transport: [native, nio]
        exclude:
          # excludes native on Windows (there's none)
          - os: windows-2019
            transport: native

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '8'
      - name: Check License
        run: ./gradlew clean spotlessCheck -PspotlessFrom='origin/${{ github.base_ref }}'
      - name: Build with Gradle
        run: ./gradlew clean check --no-daemon -PforceTransport=${{ matrix.transport }}
      - name: Archive tests output
        if: failure()
        uses: actions/upload-artifact@v1
        with:
          name: tests_output_${{ matrix.os }}_${{ matrix.transport }}
          path: reactor-netty-http/build/test-results/test/binary/output.bin